###

POST http://localhost:5000/api/auth/register/
Content-Type: application/json

{
    "email":"cm1@gmail.com",
    "name":"cm12",
    "password":"password"
}


###
POST http://localhost:5000/api/auth/login/
Content-Type: application/json

{
    "email":"cm1@gmail.com",
    "password":"password"
}
